### ISSUE TITLE
Thank you. 

### ISSUE THREAD

**Issue by gavinelder** [flosell/iam-policy-json-to-terraform#23]
Hey I just used this to move a rather large KMS policy document from inline local into a policy_document and it was a breeze.

Just wanted to say kudos you saved me an hour of my life.

**Comment by flosell** [comment]
Thank you so much for the feedback, glad you found the tool useful! 

It's rare for open source maintainers to get feedback on the impact their projects are having so really appreciate you taking the time to share yours!
