### ISSUE TITLE
Web frontend on github pages using gopherjs

### ISSUE THREAD

**Issue by nitrocode** [flosell/iam-policy-json-to-terraform#24]
I came across this project https://github.com/gopherjs/gopherjs and it seems like it would be possible to transpile golang to js and reuse the code base to build a frontend for this tool which can then be backed by github pages.

Imagine going to the website, pasting the json iam policy there, and having it convert to the terraform data source.

Low priority, nice to have, and possibly a fun weekend project for someone (maybe me...maybe 😄 )

**Comment by flosell** [comment]
That's an awesome idea, thanks for that! Actually ended up being a weekend project for me :) 

Not pretty yet but functional: https://flosell.github.io/iam-policy-json-to-terraform/

What do you think?

**Comment by flosell** [comment]
Closing this issue and creating a [bunch of new ones](https://github.com/flosell/iam-policy-json-to-terraform/issues?q=is%3Aissue+is%3Aopen+label%3Aweb-ui) to work on enhancements
