### ISSUE TITLE
Converting variable adds additional $ sign sometimes

### ISSUE THREAD

**Issue by mbaeuerle** [flosell/iam-policy-json-to-terraform#59]
Consider having this json file:
```json
{
    "Version": "2012-10-17",
    "Statement": [
      {

        "Sid": "AWSCloudTrailCreateLogStream2014110",
        "Effect": "Allow",
        "Action": [
          "logs:CreateLogStream"
        ],
        "Resource": [
          "arn:aws:logs:${data.aws_region.reg_current.name}:${data.aws_caller_identity.acc_current.account_id}:log-group:${aws_cloudwatch_log_group.trail-log-group.name}:*"
        ]

      },
      {
        "Sid": "AWSCloudTrailPutLogEvents20141101",
        "Effect": "Allow",
        "Action": [
          "logs:PutLogEvents"
        ],
        "Resource": [
          "arn:aws:logs:${data.aws_region.reg_current.name}:${data.aws_caller_identity.acc_current.account_id}:log-group:${aws_cloudwatch_log_group.trail-log-group.name}:*"
        ]
      }
    ]
}
```

Running `iam-policy-json-to-terraform` returns this:
```tf
data "aws_iam_policy_document" "policy" {
  statement {
    sid       = "AWSCloudTrailCreateLogStream2014110"
    effect    = "Allow"
    resources = ["arn:aws:logs:$${data.aws_region.reg_current.name}:${data.aws_caller_identity.acc_current.account_id}:log-group:${aws_cloudwatch_log_group.trail-log-group.name}:*"]
    actions   = ["logs:CreateLogStream"]
  }

  statement {
    sid       = "AWSCloudTrailPutLogEvents20141101"
    effect    = "Allow"
    resources = ["arn:aws:logs:$${data.aws_region.reg_current.name}:${data.aws_caller_identity.acc_current.account_id}:log-group:${aws_cloudwatch_log_group.trail-log-group.name}:*"]
    actions   = ["logs:PutLogEvents"]
  }
}

```

Notice how in the resources an extra `$` is added to the first variable: "arn:aws:logs:$_$_{data.aws_region.reg_current.name}".
The following variables however are correctly converted.

Version: 1.8.0 via Brew
OS: MacOS

**Comment by flosell** [comment]
Hi @mbaeuerle, thanks for calling this out! 

This was indeed a bug, an overly-greedy regex. 
Should be fixed now, check out your example [here](https://flosell.github.io/iam-policy-json-to-terraform/#content=%7B%0A%20%20%20%20%22Version%22%3A%20%222012-10-17%22%2C%0A%20%20%20%20%22Statement%22%3A%20%5B%0A%20%20%20%20%20%20%7B%0A%0A%20%20%20%20%20%20%20%20%22Sid%22%3A%20%22AWSCloudTrailCreateLogStream2014110%22%2C%0A%20%20%20%20%20%20%20%20%22Effect%22%3A%20%22Allow%22%2C%0A%20%20%20%20%20%20%20%20%22Action%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%22logs%3ACreateLogStream%22%0A%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%22Resource%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%22arn%3Aaws%3Alogs%3A%24%7Bdata.aws_region.reg_current.name%7D%3A%24%7Bdata.aws_caller_identity.acc_current.account_id%7D%3Alog-group%3A%24%7Baws_cloudwatch_log_group.trail-log-group.name%7D%3A*%22%0A%20%20%20%20%20%20%20%20%5D%0A%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22Sid%22%3A%20%22AWSCloudTrailPutLogEvents20141101%22%2C%0A%20%20%20%20%20%20%20%20%22Effect%22%3A%20%22Allow%22%2C%0A%20%20%20%20%20%20%20%20%22Action%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%22logs%3APutLogEvents%22%0A%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%22Resource%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%22arn%3Aaws%3Alogs%3A%24%7Bdata.aws_region.reg_current.name%7D%3A%24%7Bdata.aws_caller_identity.acc_current.account_id%7D%3Alog-group%3A%24%7Baws_cloudwatch_log_group.trail-log-group.name%7D%3A*%22%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%5D%0A%7D)
